{% set name = "datafusion" %}
{% set version = "45.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85bd37814299b989907c956f6e716e9a487b20f5e6b7a83b19f16f336bbaf387


build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - maturin >=1.8.1,<2
  host:
    - libprotobuf
    - python
    - maturin >=1.8.1,<2
    - pip
  run:
    - python
    - pyarrow >=11.0.0
    - typing_extensions

test:
  commands:
    - pip check
    - python -c "from importlib.util import find_spec; assert find_spec('datafusion')"
    - python -c "import datafusion"                                                     # [build_platform == target_platform]
  requires:
    - pip

about:
  home: https://arrow.apache.org/datafusion
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: Extensible query execution framework
  description: |
    DataFusion is an extensible query execution framework, written in Rust,
    that uses Apache Arrow as its in-memory format.
  doc_url: https://arrow.apache.org/datafusion
  dev_url: https://github.com/apache/arrow-datafusion

extra:
  recipe-maintainers:
    - cpcloud
    - andygrove
    - charlesbluca
