{% set name = "datafusion" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4c94745a30276b7a3d0c3b18a37c8da6667f397fcf3bf5bfd874cb75419c5b7


build:
  number: 0
  skip: true  # [win]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin  # [not win]    
  run:
    - python
    - numpy  # [linux]
    - pandas  # [linux]
    - pyarrow >=1
    - importlib_metadata  # [py<38]
    - importlib-metadata  # [py<38]
    - libgcc-ng  # [linux]
    - maturin  # [linux]

test:
  imports:
    - datafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arrow.apache.org/datafusion
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: Extensible query execution framework
  description: |
    DataFusion is an extensible query execution framework, written in Rust,
    that uses Apache Arrow as its in-memory format.
  doc_url: https://arrow.apache.org/datafusion
  dev_url: https://github.com/apache/arrow-datafusion

extra:
  recipe-maintainers:
    - cpcloud
    - andygrove
