{% set name = "datafusion" %}
{% set version = "39.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53f65e0e9804b0343a0bd6470c6e924a7ba4a1d6e47c1055215c35dd7c35e128


build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - maturin >=1.5.1,<1.6.0
  host:
    - libprotobuf
    - python
    - maturin >=1.5.1,<1.6.0
    - pip
  run:
    - python
    - pyarrow >=11.0.0
    - typing_extensions

test:
  imports:
    - datafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arrow.apache.org/datafusion
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: Extensible query execution framework
  description: |
    DataFusion is an extensible query execution framework, written in Rust,
    that uses Apache Arrow as its in-memory format.
  doc_url: https://arrow.apache.org/datafusion
  dev_url: https://github.com/apache/arrow-datafusion

extra:
  recipe-maintainers:
    - cpcloud
    - andygrove
    - charlesbluca
