{% set name = "datafusion" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f10e3fc61367a8017907cc0a9e0aa18dc80fd04b8b3413a90147c37a9e40bab

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
  run:
    - python
    - numpy
    - pandas
    - pyarrow
    - importlib-metadata

test:
  imports:
    - datafusion

about:
  home: https://arrow.apache.org/datafusion
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: Extensible query execution framework
  description: |
    DataFusion is an extensible query execution framework, written in Rust,
    that uses Apache Arrow as its in-memory format.
  doc_url: https://arrow.apache.org/datafusion
  dev_url: https://github.com/apache/arrow-datafusion

extra:
  recipe-maintainers:
    - cpcloud
